# permissions for end users to edit deployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-editor-role
rules:
- apiGroups:
  - apps.hurricane.cn
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.hurricane.cn
  resources:
  - deployments/status
  verbs:
  - get
